### ISSUE TITLE
Habduino on the ground

### ISSUE THREAD

**Issue by inclanfunk** [HABduino/HABduino#11]
Hi,
Could Habduino be used for tracking cars? And be adapt to receive his power from car's batteries? 
Thanks

**Comment by SanderV1** [comment]
Hello,

i was wondering if you could send your own data with a Habduino.

Thanks

**Comment by Upuaut** [comment]
Sure you can add telemetry to the telemetry construction lines that start here :

https://github.com/HABduino/HABduino/blob/master/Software/habduino_v4/habduino_v4.ino#L332

**Comment by SanderV1** [comment]
Thank you for your fast response, i tried to send my data (almost 20 floats..) but i can't get it to work properly. I just get "0" or "?" while decoding. Could you please help me with this?

Thanks

**Comment by SanderV1** [comment]
I want to send data from sensors with my habduino, any idea where I have to put the program for getting data from my sensors in the program for the habduino?

Thanks

**Comment by SanderV1** [comment]
Hello, so I tried measuring data with my Arduino uno and sending it with the HABduino. However my function doesn't get executed in the loop()...Can you please help me with this? Here's my code with the libraries.

Thanks
[HABduino.zip](https://github.com/HABduino/HABduino/files/433725/HABduino.zip)

**Comment by Upuaut** [comment]
Hi there,

Unfortunately we are unable to assist with modifying the code as its
outside of the scope of the support we can offer sorry.
