### ISSUE TITLE
Habduino_V4: 9 December 2015 Version: Does not compile

### ISSUE THREAD

**Issue by zs1jen** [HABduino/HABduino#13]
Error >  gps_ubx_checksum not declared in scope

The problem seems to be resolved by relocating the following routine and commenting it out in its original location.

void gps_ubx_checksum(uint8_t* data, uint8_t len, uint8_t* cka,
uint8_t* ckb)
{
  *cka = 0;
  *ckb = 0;
  for( uint8_t i = 0; i < len; i++ )
  {
    *cka += *data;
    *ckb += *cka;
    data++;
  }
}

bool _gps_verify_checksum(uint8_t* data, uint8_t len)

See attached file.
[habduino_v4.zip](https://github.com/HABduino/HABduino/files/93066/habduino_v4.zip)

I am still learning to program the Arduino so am not sure I have actually got this resolved properly. RTTY prints correctly on screen.  Please verify and assist.

IDE used for compile is 1.6.7

**Comment by Upuaut** [comment]
I'll get this checked but I know it compiles fine on older versions.

**Comment by zs1jen** [comment]
Thank you. I will try compiling under 1.0.5 and report back.  I may also have a version or two in between 1.05 and 1.6.7

**Comment by zs1jen** [comment]
Spot on it does compile as is from the master under 1.0.5

**Comment by Upuaut** [comment]
Ok thanks. I'll mark this as closed for the moment. You are welcome to try
Dave Akermans flextrack
https://github.com/daveake/FlexTrack

Its default board is Habduino.

Cheers
