### ISSUE TITLE
Habduino_V4: 9 December 2015 Version: APRS issue

### ISSUE THREAD

**Issue by zs1jen** [HABduino/HABduino#14]
I am not sure if APRS is decoding properly or even being transmitted. 144.800MHz.  aprs.fi shows no data when using Habduino_V4.

**Comment by Upuaut** [comment]
Did you uncomment :

https://github.com/HABduino/HABduino/blob/master/Software/habduino_v4/ax25modem.h#L20
?

**Comment by zs1jen** [comment]
Good evening,  
Thank you for responding. 
If by Line 20 you are referring to
#define APRS // Uncomment to use APRS.
Then yes I can confirm I did uncomment it.
I also changed
 #define APRS_CALLSIGN "ZS1JEN"  in the ax25modem
as well as in the habduino_v4.ino.  I changed it back to "changeme" before I submitted the change I made to gps check routine.
Regards

Andre

**Comment by zs1jen** [comment]
APRS position reports are now being logged on aprs.fi.  No telemetry though.

**Comment by Upuaut** [comment]
Hi there. Telemetry via APRS is part of this feature request:
https://github.com/HABduino/HABduino/issues/10
We will probably move over to Dave Akermans Flextrack code base shortly, we have no plans to develop this code further at this time.
