### ISSUE TITLE
How do I change the frequency for the APRS to 144.93

### ISSUE THREAD

**Issue by DiegoGLagash** [HABduino/HABduino#16]
I'm preparing my flight in Argentina and I'll like to change the APRS to our local frequency. I've search though the code but I did not found. Do you know how to change that?

Thanks,

**Comment by Upuaut** [comment]
You don't. The HX1 module is a fixed frequency unit so it literally is what it says on the can. Did you get a HX1 with the unit ?

**Comment by DiegoGLagash** [comment]
No is a separate chip that I'll add it later. I was looking in the code and
I did not find the parameter.

**Comment by Upuaut** [comment]
Because its not there :) I'll close this off.
