### ISSUE TITLE
GPS Locking Issues

### ISSUE THREAD

**Issue by Laserman** [HABduino/HABduino#17]
GPS will very rarely acquire a lock, when it does it is not very consistent. This is on the V4.1 board, red light will blink indefinitely, never transmits APRS.

**Comment by gurlavie** [comment]
Just from my experience - are yo operating from a battery ?
I found out that when a terry voltage is too low - the system operates, but
no Gps lock, or the lock is acquired for a very short time.

**Comment by Upuaut** [comment]
No/long lock times aren't a coding issue indicating some other issue with the hardware. As Gur advises please run from battery also please try another antenna. If you suspect the hardware is faulty please contact Uputronics to discuss.
